Update download instructions and sumarize them in a central place
lf-lang/lf-lang.github.io pull request #165
Opened 2023-09-13 17:01 UTC by cmnrd

This PR updates the download page (e.g. it includer instructions for installing via AUR), and it reduces redundancy by bundling all download instructions on the download page. Consequently, the scope of the tools sections in the handbook changes, and they should now only provide usage instructions. With this change, they look really empty... and we should make an effort to fill those pages in subsequent PR.

I also removed the Troubleshooting section for Python, as I believe this is outdated and most of it, should be fixed by generating launch scripts in bin.

2023-09-13 18:59 UTC, lhstrh commented
I think this makes sense. We should go into more detail about using the tools on those other pages; I agree that just padding those with redundant installation instructions isn't very helpful...

2023-09-14 10:23 UTC, edwardalee requested changes
The command-line installation tools do not include how to install the nightly build. They should.  For the VS Code instructions, the instructions for switching to the pre-release version should be in their own paragraph.

2023-09-14 14:57 UTC, cmnrd commented
Yes, I hadn't updated the CLI instructions yet. The PR is now ready for review (please see the updated PR description). I also updated the VS Code section as requested by Edward and made some additional changes to math the style with the other sections.

2023-09-20 00:06 UTC, lhstrh reviewed
Looks good like a good reorganization but I noticed a bunch of typos just by reading through it. I would run this through a spell checker before merging it.

2023-09-20 00:06 UTC, lhstrh commented on packages/lingua-franca/src/templates/pages/download.tsx
> +      <p>Our Visual Studio Code extensios can be installed via the Marketplace or build from source as detailed below.
```suggestion
      <p>Our Visual Studio Code extension can be installed via the Marketplace or build from source as detailed below.
```

2023-09-20 00:06 UTC, lhstrh commented on packages/lingua-franca/src/templates/pages/download.tsx
> +          <p>Please refer to the <a href="https://github.com/lf-lang/vscode-lingua-franca">Lingua Franca Code Extension GitHub repository</a> for build instructions.</p>
```suggestion
          <p>Please refer to the <a href="https://github.com/lf-lang/vscode-lingua-franca">Lingua Franca VS Code GitHub repository</a> for build instructions.</p>
```

2023-09-20 00:06 UTC, lhstrh commented on packages/lingua-franca/src/templates/pages/download.tsx
> +          <p>There are binary packages availabe in the Arch user repository, which you can install using your favourite AUR helper. For instance, with yay:
```suggestion
          <p>There are binary packages available in the Arch user repository, which you can install using your favorite AUR helper. For instance, with <code>yay</code>:
```

2023-09-20 08:32 UTC, cmnrd commented
Hmm, looks like my normal spell checker doesn't like .tsx files. I run the changes through an external checker and pushed several fixes.

2023-09-20 16:41 UTC, lhstrh commented
@edwardalee: can we go ahead with merging this, or is there still anything you'd like to see changed?

2023-09-20 16:58 UTC, edwardalee approved these changes
OK, Looks good to me.

2023-09-21 00:25 UTC, merged