Description of reaction declarations in C++
lf-lang/lf-lang.github.io pull request #167
Opened 2023-09-15 14:15 UTC by cmnrd

Closes #154

2023-09-20 08:33 UTC, cmnrd commented
Ok if I merge this?

2023-09-20 12:15 UTC, edwardalee requested changes
This looks like a good start, but the ability to optionally add a name to a reaction is nowhere explained specifically nor is the requirement that a reaction declaration be named.  I've suggested also some grammar fixes.

2023-09-20 12:15 UTC, edwardalee commented on packages/documentation/copy/en/topics/Reaction Declarations.md
> +In this case, the compiler will generate two header files `A/Foo.hh` and `sub/B/Bar.hh`, which would need to be included by a an external implementation file.
```suggestion
In this case, the compiler will generate two header files `A/Foo.hh` and `sub/B/Bar.hh`, which would need to be included by an external implementation file.
```

2023-09-20 12:15 UTC, edwardalee commented on packages/documentation/copy/en/topics/Reaction Declarations.md
> +The precise method signature depends on the name of the reactor, the name of the reactions and the precise triggers, sources and effects that are defined in the LF code.
```suggestion
The precise method signature depends on the name of the reactor, the name of the reactions and the precise triggers, sources, and effects that are defined in the LF code.
```

2023-09-20 13:29 UTC, cmnrd commented
> but the ability to optionally add a name to a reaction is nowhere explained specifically nor is the requirement that a reaction declaration be named

That is a good point. I just extended upon the existing C text, but it seems like some basics are missing. Actually, the reaction page even lacks an introduction of the basic components in a reaction (i.e., sources, triggers, offset) and I also couldn't find an explanation elsewhere. I'll take a stab at this.

2023-09-27 17:43 UTC, cmnrd commented on packages/documentation/copy/en/topics/Reaction Declarations.md
> +Sometimes, it is inconvenient to mix Lingua Franca code with target code. Rather than _defining_ reactions (i.e., complete with inlined target code), it is also possible to just _declare_ them, and p
Actually, we do not enforce names if the body is missing. I think this is ok as we have a well-defined name anyway. Of course, it is more convenient to use names, but I don't see the need to enforce this in the validator.

2023-09-27 17:45 UTC, cmnrd commented
I gave the description of reactions a significant overhaul. Please check if the changes are sensible. There might still be a few rough spots, but I think all in all this is a significant improvement.

2023-09-30 15:00 UTC, edwardalee requested changes
Looks great!!  Thanks for updating this.  I've suggested some edits.

2023-09-30 15:00 UTC, edwardalee commented on packages/documentation/copy/en/topics/Reactions.md
> +which could look something like this:
```suggestion
The `files` target property is used to make accessible the file that has the implementation in `hello.c,
which could look something like this:
```

2023-09-30 15:00 UTC, edwardalee commented on packages/documentation/copy/en/topics/Reactions.md
> +was generated from the Lingua Franca source file when the LF program was compiled. The file
```suggestion
In the above example, the C file uses `#include` to import a file called `HelloDecl.h`. The `HelloDecl.h` file
is generated from the Lingua Franca source file when the LF program is compiled. The file
```

2023-09-30 15:00 UTC, edwardalee commented on packages/documentation/copy/en/topics/Reactions.md
> +will look something like this:
```suggestion
As another example, if an LF program consists of files `F1.lf` and `F2.lf`, where `F1.lf` defines reactors
`A` and `B` and `F2.lf` defines the reactor `C` and the main reactor `F2`, then the directory structure
will look something like this:
```

2023-09-30 15:00 UTC, edwardalee commented on packages/documentation/copy/en/topics/Reactions.md
> +the describe the signatures of the reaction functions that you must implement.
```suggestion
they describe the signatures of the reaction functions that you must implement.
```

2023-09-30 15:00 UTC, edwardalee commented on packages/documentation/copy/en/topics/Reactions.md
> +This is done using the syntax
```suggestion
The file referenced by the `cmake-include` target property has the following syntax:
```

2023-09-30 15:00 UTC, edwardalee commented on packages/documentation/copy/en/topics/Reactions.md
> +Using the `cmake-include` target property, we can make the build system aware of this externally supplied implementation. The contents of `hello.cmake` is as follows:
```suggestion
Using the `cmake-include` target property, we can make the build system aware of this externally supplied implementation. The contents of `hello.cmake` is as follows:

```

2023-09-30 15:00 UTC, edwardalee commented on packages/documentation/copy/en/topics/Reactions.md
> +In order to provide an implementation of a reaction method, it is important to know the header file that declares the reactor class as well as the precise signature of the method implementing the rea
```suggestion
In order to provide an implementation of a reaction method, it is important to know the header file that declare the reactor class as well as the precise signature of the method implementing the reaction body.
```

2023-09-30 15:00 UTC, edwardalee commented on packages/documentation/copy/en/topics/Reactions.md
> +The precise method signature depends on the name of the reactor, the name of the reactions and the precise triggers, sources, and effects that are defined in the LF code.
```suggestion
The precise method signature depends on the name of the reactor, the name of the reactions, and the precise triggers, sources, and effects that are defined in the LF code.
```

2023-10-05 13:02 UTC, cmnrd commented on packages/documentation/copy/en/topics/Methods.md
> +The $method$ keyword can optionally be prefixed with the $const$ qualifier, which indicates that the method is read only.
Good catch. A const method has read read-only access to the state variables. I updated the text.

2023-10-05 13:03 UTC, cmnrd commented
Thanks for the detailed suggestions @edwardalee! I committed your suggestions and made a small adjustment. Could you approve the PR if you think this is ready to go?

2023-10-05 18:24 UTC, edwardalee approved these changes
LGTM!

2023-10-05 18:24 UTC, merged